apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: macpaw-provider-secret
type: Opaque
stringData:
  token: $CF_API_TOKEN
---
apiVersion: cloudflare.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: macpaw
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: macpaw-provider-secret
      key: token
